### ISSUE TITLE
Nit: Typo in description

### ISSUE THREAD

**Issue by delsonting** [Mikeulrich75/GAProductArrayBuilder#2]
Thanks for submitting this template, it has been approved and should appear in the gallery in the next 24 hours.

template.tpl
"description": "Build a GA Enhanced or Standard **Ecommace** product array variable using any site's product object by mapping the original object's key value into each value of the properly formatted GA product object.",
When updating the template.tpl file, please update the metadata.yaml file as well to use the new template.tpl version.

**Comment by Mikeulrich75** [comment]
Thanks for the heads up, I have fixed the typo and updated the SHA value to the proper commit version. This is ready to publish. :)
