### ISSUE TITLE
Nested object

### ISSUE THREAD

**Issue by chestnutroasting** [Mikeulrich75/GAProductArrayBuilder#3]
Hello!
I have a product data layer that sometime contains a nested object, like this one:
'products' : [{
       'brand' : '<brand name>',
       'name' : '<product name>',
       'sku' : '<sku>',
       'option' : {
         'option1': '<true|false>',
         'option2' : '<true | false>'
      }
   },
{
       'brand' : '<brand name>',
       'name' : '<product name>',
       'sku' : '<sku>'
}]

I want to be able to map option.option1 and option.option2 to a custom dimension.

I modified your template to do something like this where I added the option variable:

const option = 'option';

if (type == 'array') {
    products.forEach(function(element) {
        productArray.push({
            dimension: element[option][dimensionParam]
        });
    });
return productArray;

This works well if all the products in the array contains the nested option object. If one product has it and the other one doesn't, the whole thing returns FALSE. How could I make sure all products are correctly returned and mapped to the according GA friendly variable?

Thank you!

**Comment by Mikeulrich75** [comment]
Hello,

Sorry for the very long delay in response. After reviewing your issue, the solution follows the recommended structure Google uses in their dataLayers, and they don't use nested objects in product arrays. Trying to update the template to use your unique use case could potentially make the code unstable, hence why you're seeing it fail in the loop when the option object is missing. My recommended approach would be to push both option 1 and option2 in their own unique key value pairs and the solution is designed to capture and pass the value if it exists in any of the product objects. It shouldn't fail in this scenario. 

Hope this helps, and sorry it took way to long for me to get back to you! 🤦🏼 
Mike Ulrich

**Comment by chestnutroasting** [comment]
Hello,

I ended up finding another solution that works. Unfortunately, avoiding nested objects was not possible. Here's what I did for future reference in case someone else runs into a similar issue.

Instead of starting with the if condition, I placed it after the mapping of the main variables.

```
products.forEach(function(element) {
  var product = {
            brand: element[brandParam],
            sku: element[skuParam],
            name: element[nameParam]
  };
if(element[option]) {
  product.dimension1 = element[option][option1];
  product.dimension2 = element[option][option2];
}
productArray.push(product);
});
```


This has been working well, so hopefully it'll be useful for anyone who needs to modify your template.
